# © 2025 Maximilian Marx
# SPDX-FileContributor: Maximilian Marx
#
# SPDX-License-Identifier: EUPL-1.2

[bans]
multiple-versions = "deny"
wildcards = "deny"

[licenses]
unused-allowed-license = "warn"
allow = ["EUPL-1.2", "MIT", "ISC", "Apache-2.0", "Unicode-3.0"]
